### ISSUE TITLE
sample.py missing

### ISSUE THREAD

**Issue by LukasMosser** [hvy/chainer-gan-improvements#1]
I'd love to give this a try, but sample.py seems to be missing.

Any chance, we could get a commit of sample.py so I can try out the sampling as well?

Many thanks!

**Comment by hvy** [comment]
Thanks for pointing out!

I added the script so you should be able to run the sample command in the README.

If you'd like to take snapshots during the training you could also pass the generated images of shape `(n_batch, n_channel, width, height)` to `plot.save_ims()` which is exactly what I am doing in the sample script.

**Comment by LukasMosser** [comment]
Awesome thanks!
